### ISSUE TITLE
request to enable ath10k driver to support Atheros QCA9x based mPCIe wifi chipset

### ISSUE THREAD

**Issue by npatil-boosterfuels** [balena-os/balena-iot-gate-imx8#135]
Hello, 

Requesting to include kernel options CONFIG_ATH10K and CONFIG_ATH10K_PCI along with linux-firmware-ath10k package in default image. We have successfully tested mPCI wifi cards with QCA9984/QCA9880 chipset with ath10k  driver on iot-gate-imx8. Driver also supports few other Atheros chipset as well.

Currently, iot-gate-imx8's built-in Intel ax200 wifi card fails to provide sufficient range for our field operations. So we want to revert to tried and tested wifi cards that worked for us in the past.

Regards,
-Npatil

**Comment by npatil-boosterfuels** [comment]
Just wanted to check if there are any concerns/comments on this request. It will greatly help avoid maintaining custom Yocto and open-up up possibility of handful of Atheros wifi chips for any future users.

**Comment by npatil-boosterfuels** [comment]
Hello,

I see ath10k driver added by pr https://github.com/balena-os/balena-iot-gate-imx8/pull/161. Thank you for addressing this request. It's a huge help! When this change will be available for official image download via fleet dashboard?

Regards,
-Niranjan

**Comment by acostach** [comment]
Hi @npatil-boosterfuels, the image v2.108.1 has been released in the production cloud includes this change.
