### ISSUE TITLE
No wireless-regdb package installed in hostOS

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-iot-gate-imx8#139]
The `wireless-regdb` package contains the regulatory domain database that is required for a working wireless. This package is added as part of the `packagegroup-balena-connectivity` recipe in meta-balena, however this DT has:
```
BBMASK += "packagegroup-balena-connectivity.bbappend"
```
As part of its `conf/layer.conf` device integration layer.

It's unclear why this was done like this in the first place - the correct approach to modify this recipe would be to override it in the integration layer itself instead of ignoring it.

**Comment by acostach** [comment]
Fix present in 2.108.1 
```
[   11.396074] cfg80211: Loading compiled-in X.509 certificates for regulatory database
```
