### ISSUE TITLE
Deploy v2.82.2+rev2 to production

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-iot-gate-imx8#22]
This release contains a NFSD kernel configuration that is required by a customer's application.

**Comment by alexgg** [comment]
Test plan available in https://resinio.testlodge.com/projects/16238/runs/608734?tab=0

**Comment by acostach** [comment]
Will be released with BalenaOS version v2.82.10 from https://github.com/balena-os/balena-iot-gate-imx8/pull/23

**Comment by acostach** [comment]
v2.82.10+rev1 released to production for iot-gate-imx8
