### ISSUE TITLE
eth0 not working on latest rev boards with balenaOS 2.85.2+rev1

### ISSUE THREAD

**Issue by npatil-boosterfuels** [balena-os/balena-iot-gate-imx8#41]
Hello,
Recently we received latest revision eval kit of iot-gate-imx8 and are unable to get eth0 to work. eth0 led keeps going on/off and is not able to exchange packets. eth1 works fine. Eth0 was not an issue with earlier rev boards and BalenaOS.
Please note, eth0 works just fine on base os shipped from Compulab. The issue only happens after running balenaOS.

Please let me know if you need additional info.
`
root@xxxx:~# cat /etc/os-release     
ID="balena-os"
NAME="balenaOS"
VERSION="2.85.2+rev1"
VERSION_ID="2.85.2+rev1"
PRETTY_NAME="balenaOS 2.85.2+rev1"
MACHINE="iot-gate-imx8"
META_BALENA_VERSION="2.85.2"
BALENA_BOARD_REV="fba8222"
META_BALENA_REV="34a41e07"
SLUG="iot-gate-imx8"

serialpn=IOT-GATE-iMX8-D4-NA32-WB-JS7600G-XL-TIC-FARS4-FBCAN-V100-220414-0001c0306683

`

**Comment by npatil-boosterfuels** [comment]
Just an update from Compulab that the Ethernet PHY was updated to Realtek RTL8211E so following patches need to be integrated. is it possible to get this integrated in base balenaOS or do we have to build custom image with patches integrated?

* U-Boot:
https://github.com/compulab-yokneam/meta-bsp-imx8mm/blob/iot-gate-imx8_r3.0/recipes-bsp/u-boot/compulab/imx8mm/0125-imx8mm-net-enable-phy-Realtek-RTL8211E.patch
* Kernel:
https://github.com/compulab-yokneam/meta-bsp-imx8mm/blob/iot-gate-imx8_r3.0/recipes-kernel/linux/compulab/imx8mm/0078-ucm-imx8m-mini-dts-phy-eliminate-excessive-reset.patch

**Comment by acostach** [comment]
Hi @npatil-boosterfuels , we've merged the BSP update that includes in the patches you mentioned, if you want to test them out before the image will become available in the cloud you can do a local yocto build of the master branch.

**Comment by npatil-boosterfuels** [comment]
> Hi @npatil-boosterfuels , we've merged the BSP update that includes in the patches you mentioned, if you want to test them out before the image will become available in the cloud you can do a local yocto build of the master branch.

Great! Thank you for the update @acostach.
